<?php

$core_journal = array(

"Academic medicine : Journal of the Association of American Medical Colleges",
"AJR. American Journal of Roentgenology", 
"American Family Physician", 
"American Heart Journal", 
"American Journal of Clinical Pathology",
"American Journal of Obstetrics and Gynecology", 
"American Journal of Ophthalmology", 
"American Journal of Pathology", 
"American Journal of Physical Medicine & Rehabilitation / Association of Academic Physiatrists", 
"American Journal of Public Health", 
"American Journal of Respiratory and Critical Care Medicine",
"American Journal of Surgery",
"Anaesthesia",
"Anesthesia and Analgesia", 
"Anesthesiology", 
"Annals of Emergency Medicine", 
"Annals of Internal Medicine", 
"Annals of Surgery", 
"Archives of Dermatology", 
"Archives of Disease in Childhood",
"Archives of Disease in Childhood. Fetal and Neonatal Edition", 
"Archives of Environmental Health", 
"Archives of General Psychiatry", 
"Archives of Internal Medicine", 
"Archives of Neurology", 
"Archives of Ophthalmology", 
"Archives of Otolaryngology--Head & Neck Surgery", 
"Archives of Pathology & Laboratory Medicine", 
"Archives of Pediatrics & Adolescent Medicine", 
"Archives of Physical Medicine and Rehabilitation", 
"Archives of surgery (Chicago, Ill. : 1960)", 
"Arthritis and Rheumatism", 
"Blood", 
"BMJ",
"Brain; A Journal of Neurology",
"British Journal of Obstetrics and Gynaecology", 
"British Medical Journal", 
"CA: A Cancer Journal for Clinicians",
"Canadian Medical Association journal",
"Cancer", 
"Chest", 
"Circulation",
"Clinical Orthopaedics and Related Research", 
"Clinical Pediatrics", 
"Clinical Pharmacology and Therapeutics", 
"CMAJ",
"Cochrane Database Syst Rev",
"Critical Care Medicine", 
"Current Problems in Surgery", 
"Diabetes", 
"Digestive Diseases and Sciences", 
"Disease-a-month : DM",
"Endocrinology", 
"Gastroenterology", 
"Geriatrics", 
"Gut", 
"Heart", 
"Heart & Lung; the Journal of Critical Care", 
"Hospital Practice", 
"Hospitals & Health Networks / AHA", 
"JAMA : the journal of the American Medical Association",
"Journal of Clinical Pathology", 
"The Journal of Immunology", 
"Journal of Neurosurgery", 
"Journal of Oral and Maxillofacial Surgery :  Official Journal of the American Association of Oral and Maxillofacial Surgeons", 
"Journal of the American College of Cardiology", 
"Journal of the American College of Surgeons", 
"Journal of the American Dietetic Association", 
"Journal of Toxicology. Clinical Toxicology", 
"The Journal of Trauma", 
"The Journal of Urology", 
"The Journals of Gerontology. Series A, Biological Sciences and Medical Sciences", 
"The JournalS of Gerontology. Series B, Psychological Sciences and Social Sciences", 
"Lancet", 
"Mayo Clinic Proceedings", 
"Medical Letter on Drugs and Therapeutics", 
"Medicine; Analytical Reviews of General Medicine, Neurology, Psychiatry, Dermatology, and Pediatries", 
"Neurology", 
"Nursing Clinics of North America", 
"Nursing Outlook", 
"Nursing Research", 
"Obstetrics and Gynecology", 
"Pediatric Clinics of North America", 
"Pediatrics", 
"Physical Therapy", 
"Plastic and Reconstructive Surgery", 
"Postgraduate Medicine", 
"Progress in Cardiovascular Diseases", 
"Public health reports",
"Radiologic Clinics of North America", 
"Radiology", 
"Southern Medical Journal", 
"Surgery", 
"Surgical Clinics of North America", 
"The American Journal of Cardiology", 
"The American Journal of Clinical Nutrition", 
"The American Journal of Medicine", 
"The American Journal of Nursing", 
"The American Journal of Psychiatry", 
"The American Journal of the Medical Sciences", 
"The American Journal of Tropical Medicine and Hygiene", 
"The Annals of Otology, Rhinology, and Laryngology", 
"The Annals of Thoracic Surgery", 
"The British Journal of Radiology", 
"The British Journal of Surgery", 
"The Journal of allergy and clinical immunology", 
"The Journal of Bone and Joint Surgery", 
"The Journal of Bone and Joint Surgery.  British volume", 
"The Journal of Clinical Endocrinology and Metabolism", 
"The Journal of Clinical Investigation", 
"The Journal of Family Practice", 
"The Journal of Infectious Diseases", 
"The Journal of Laboratory and Clinical Medicine", 
"The Journal of Laryngology and Otology", 
"The Journal of Nervous and Mental Disease", 
"The Journal of Nursing Administration", 
"The Journal of Pediatrics", 
"The Journal of Thoracic and Cardiovascular Surgery", 
"The Medical Clinics of North America", 
"The New England Journal of Medicine", 
"The Orthopedic Clinics of North America", 
"The Urologic Clinics of North America", 
"The Western Journal of Medicine"

);
?>